spring.application.name=ms-gestion-guias
server.port=8080

# EFS
app.efs.path=${EFS_PATH:/app/efs}

# AWS S3
app.s3.bucket=${S3_BUCKET:bucket-guias-despacho}
app.aws.region=${AWS_REGION:us-east-1}

# Azure AD B2C
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cloudnativeduocuc1.b2clogin.com/791de5e6-4bf3-41a3-98af-9afbeb71f387/v2.0/

# jwks_uri obtenido en Azure
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cloudnativeduocuc1.b2clogin.com/cloudnativeduocuc1.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1_duocdemoazure_login_registro