spring.application.name=ms-gestion-guias

# Puerto de la aplicación
server.port=${SERVER_PORT:8081}

# ========================================
# EFS
# ========================================

app.efs.path=${EFS_PATH:/app/efs}

# ========================================
# AWS S3
# ========================================

app.s3.bucket=${S3_BUCKET:guias-de-despacho}
app.aws.region=${AWS_REGION:us-east-1}

# ========================================
# AZURE AD B2C
# ========================================

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cloudnativeduocuc1.b2clogin.com/791de5e6-4bf3-41a3-98af-9afbeb71f387/v2.0/

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cloudnativeduocuc1.b2clogin.com/cloudnativeduocuc1.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1_duocdemoazure_login_registro

# ========================================
# RABBITMQ
# ========================================

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

# ========================================
# ORACLE CLOUD
# ========================================

spring.datasource.url=jdbc:oracle:thin:@${ORACLE_TNS_ALIAS:j6m47aosy5zpydbv_high}?TNS_ADMIN=${ORACLE_WALLET_PATH:C:/Oracle/Wallet_J6M47AOSY5ZPYDBV}

spring.datasource.username=${ORACLE_USERNAME:ADMIN}
spring.datasource.password=${ORACLE_PASSWORD:Evalley1995.}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ========================================
# JPA / HIBERNATE
# ========================================

# Valida que la tabla y sus columnas existan en Oracle.
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false