name: Preparar llave SSH
env:
    EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
run: |
    mkdir -p ~/.ssh
  printf '%s\n' "$EC2_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  chmod 600 ~/.ssh/id_rsa

name: Validar llave SSH
run: |
    ssh-keygen -y -f ~/.ssh/id_rsa > /dev/null
    echo "La llave SSH tiene un formato válido"

name: Probar conexión SSH
run: |
    ssh -i ~/.ssh/id_rsa \
    -o BatchMode=yes \
    -o ConnectTimeout=15 \
    -o StrictHostKeyChecking=no \
    "${{ secrets.USER_SERVER }}@${{ secrets.EC2_HOST }}" \
    "echo 'Conexión SSH exitosa'"

name: Desplegar en EC2
run: |
    ssh -i ~/.ssh/id_rsa \
    -o StrictHostKeyChecking=no \
    "${{ secrets.USER_SERVER }}@${{ secrets.EC2_HOST }}" << 'EOF'

    echo "${{ secrets.DOCKERHUB_TOKEN }}" | \
    sudo docker login \
      -u "${{ secrets.DOCKERHUB_USERNAME }}" \
      --password-stdin

    sudo docker pull \
    "${{ secrets.DOCKERHUB_USERNAME }}/ms-gestion-guias:latest"

    sudo docker stop ms-gestion-guias || true
    sudo docker rm ms-gestion-guias || true

    sudo docker run -d \
      --name ms-gestion-guias \
      --restart unless-stopped \
      -p 8080:8080 \
      -v /mnt/efs:/app/efs \
      -e EFS_PATH=/app/efs \
      -e S3_BUCKET="${{ secrets.S3_BUCKET }}" \
      -e AWS_REGION="${{ secrets.AWS_REGION }}" \
      -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
      -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
      -e AWS_SESSION_TOKEN="${{ secrets.AWS_SESSION_TOKEN }}" \
      "${{ secrets.DOCKERHUB_USERNAME }}/ms-gestion-guias:latest"

          EOF
